### ISSUE TITLE
Does every operation require a tag?

### ISSUE THREAD

**Issue by fauskanger** [lukeautry/openapi-ts-client-gen#1]
Hello, I'm using tsoa in my project and I am in the process of trying to use open-api-ts-client-gen. Thanks for your efforts and work on both projects!

I get an error message when I try to generate client (using CLI version):

> $> `node node_modules/openapi-ts-client-gen/dist/cli.js -n Api -f ../path/to/swagger.json -o ./out/swagger.json`
> 
> Error: no tags for {"get":{"operationId":"getAllUsers","produces":["application/json"],"responses":{"200":{"description":"Ok","schema":{"type":"array","items":{"$ref":"#/definitions/User"}}}},"security":[],"parameters":[]}}

Based on the [tsoa README][tsoaOI], I get the impression that `OperationId` is required for client SDK generation, but not tags. I see in [this line][requireTag] that _both_ operationId and tags are required, but a [few lines below][ifTag] there is a test to see whether there is a tag at all - which made me raise this question.

Excerpt is included below: 
    
    // generate-client.ts
    // ...
    if (!operation.operationId || !operation.tags) {
      throw new Error("no tags for " + JSON.stringify(path));
    }
    
    const tag = operation.tags[0];
    const service = (serviceMap[tag] = serviceMap[tag] || {
      name: `${tag}Service`,
      operations: []
    });
    
    let operationId = operation.operationId.replace("_", "");
    if (tag) {
      operationId = operationId.replace(tag, "");
    }
    // ...

Perhaps I don't have a correct idea of what it _is_, but I'm assuming it will generate some api models, api calls; or scaffolded code based on the given swagger.json file.

[requireTag]: https://github.com/lukeautry/openapi-ts-client-gen/blob/master/src/generate-client.ts#L335
[ifTag]: https://github.com/lukeautry/openapi-ts-client-gen/blob/master/src/generate-client.ts#L346
[tsoaOI]: https://github.com/lukeautry/tsoa#operationid

**Comment by lukeautry** [comment]
@fauskanger Currently, yes, every operation has to have a tag so that methods can get grouped into a service. I'd be open to using some alternative to this approach, but it worked pretty well for my use case.

**Comment by fauskanger** [comment]
Thanks, @lukeautry, for your answer. I will use tags as well. I don't have any better approaches, but now I understand what the tags are for.
