### ISSUE TITLE
No definitions

### ISSUE THREAD

**Issue by fantapop** [lukeautry/openapi-ts-client-gen#10]
Hey, Not sure if I'm doing something wrong.  I'm hitting this error:

https://github.com/lukeautry/openapi-ts-client-gen/blob/3c17ed0c4750438fc7dbb3c4f6f006af8a8f7cea/src/generate-client.ts#L310

My swagger spec is v3 and generated using tsoa.  Should there be a definitions block?

**Comment by fantapop** [comment]
Ah, it looks like definitions is an open api v2 thing and not a v3 thing.  It would be helpful to put in the README that it only supports v2.

**Comment by lukeautry** [comment]
v3 has been supported for a while now
